local util = require("unixtime_utils.util")

describe("util.normalize_epoch", function()
  it("accepts 13-digit ms", function()
    local s = util.normalize_epoch("1716403200000", true, true) -- 2024-05-23 00:00:00 UTC
    assert.is_number(s)
    assert.equals(1716403200, s)
  end)
  it("accepts 10-digit seconds", function()
    local s = util.normalize_epoch("1716403200", true, true)
    assert.equals(1716403200, s)
  end)
  it("rejects 13-digit when not allowed", function()
    local s = util.normalize_epoch("1716403200000", true, false)
    assert.is_nil(s)
  end)
  it("rejects invalid length", function()
    local s = util.normalize_epoch("123", true, true)
    assert.is_nil(s)
  end)
end)

describe("util.build_virt_text", function()
  it("builds table with prefix and highlight", function()
    local vt = util.build_virt_text("hello", "Comment", " >> ")
    assert.same({ { " >> hello", "Comment" } }, vt)
  end)
  it("defaults prefix", function()
    local vt = util.build_virt_text("world", "Identifier")
    assert.same({ { " ⏰ world", "Identifier" } }, vt)
  end)
end)
